UPDATE FUELS SET NAME = 'ДП-Л-Евро5-В0' WHERE FUEL_ID = 7;

UPDATE FUELS SET NAME = 'VP ДП-Л-Евро5-В0' WHERE FUEL_ID = 8;

UPDATE MIGRATEOPTIONS SET SVALUE = '20190621' WHERE MIGRATEOPTION_ID = 3400;

UPDATE MIGRATEOPTIONS SET SVALUE = '6' WHERE MIGRATEOPTION_ID = 3410;

commit;
