#ifndef PAGELIST_H
#define PAGELIST_H
enum {
    INTRO_PAGE,
    SELECT_TERMINAL_PAGE,
    SHOW_FUELNAME_PAGE,
    CHANGE_FUELNAME_PAGE,
    SET_AZS_FUELNAME_PAGE,
    FINAL_PAGE
};
#endif // PAGELIST_H
